# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Events
    url: events
    weight: 10
  - name: News
    url: news
    weight: 20
  - name: People
    url: people
    weight: 30
  - name: Alumni
    url: alumni
    weight: 40
  - name: Seminars
    url: seminar
    weight: 50
  - name: Publications
    url: publication
    weight: 60
  - name: Deadlines
    url: deadlines
    weight: 70
  - name: Contact
    url: contact
    weight: 80
